version: "3.9"

services:
  front-end:
    image: micro-restaurant/self-service-kiosk:1.0
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    depends_on:
      - ${GATEWAY}
      - ${MENU_SERVICE}
      - ${KITCHEN_SERVICE}
      - ${DINING_SERVICE}
    environment:
      - REACT_APP_GATEWAY=${GATEWAY}:3000
      - REACT_APP_MENU_URL=localhost:9500/menu
      - REACT_APP_KITCHEN_URL=localhost:9500/kitchen
      - REACT_APP_DINING_URL=localhost:9500/dining
      - REACT_APP_CONFIG=fm
      - PORT=${FRONT_PORT}
    networks:
      - nestjs-restaurant-network

  front-end-bff:
    image: micro-restaurant/self-service-kiosk:1.0
    depends_on:
      - bff
    ports:
      - "${FRONT_BFF_PORT}:${FRONT_BFF_PORT}"
    environment:
      - REACT_APP_BFF_HOST=localhost:${BFF_PORT}
      - REACT_APP_CONFIG=bff
      - PORT=${FRONT_BFF_PORT}
    networks:
      - nestjs-restaurant-network

  bff:
    image: micro-restaurant/bff:1.0
    ports:
      - "${BFF_PORT}:${BFF_PORT}"
    depends_on:
      - ${GATEWAY}
      - ${MENU_SERVICE}
      - ${KITCHEN_SERVICE}
      - ${DINING_SERVICE}
    environment:
      - GATEWAY_URL_WITH_PORT=${GATEWAY}:3000
      - MENU_SERVICE_URL_WITH_PORT=${GATEWAY}:3000/menu
      - KITCHEN_URL=${GATEWAY}:3000/kitchen
      - DINING_SERVICE_URL_WITH_PORT=${GATEWAY}:3000/dining
      - BFF_PORT=${BFF_PORT}
    networks:
      - nestjs-restaurant-network
    restart: always

  interactive-table:
    image: micro-restaurant/interactive-table:1.0
    ports:
      - "${INTERACTIVE_TABLE_PORT}:${INTERACTIVE_TABLE_PORT}"
    depends_on:
      - interactive-table-bff
    environment:
      PORT: ${INTERACTIVE_TABLE_PORT}
      REACT_APP_BFF_HOST: localhost:${INTERACTIVE_TABLE_BFF_PORT}
    networks:
      - nestjs-restaurant-network

  interactive-table-bff:
    image: micro-restaurant/interactive-table-bff:1.0
    ports:
      - "${INTERACTIVE_TABLE_BFF_PORT}:${INTERACTIVE_TABLE_BFF_PORT}"
    environment:
      PORT: ${INTERACTIVE_TABLE_BFF_PORT}
      GATEWAY: ${GATEWAY}
      MENU: ${GATEWAY}:3000/menu
      KITCHEN: ${GATEWAY}:3000/kitchen
      DINING: ${GATEWAY}:3000/dining
    depends_on:
      - ${GATEWAY}
    networks:
      - nestjs-restaurant-network

networks:
  nestjs-restaurant-network:
    driver: bridge