version: "3.9"

services:
  front-end:
    image: micro-restaurant/self-service-kiosk
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    depends_on:
      - ${GATEWAY}
      - ${MENU_SERVICE}
      - ${KITCHEN_SERVICE}
      - ${DINING_SERVICE}
    environment:
      - REACT_APP_GATEWAY=${GATEWAY}:3000
      - REACT_APP_MENU_URL=localhost:9500/menu
      - REACT_APP_KITCHEN_URL=localhost:9500/kitchen
      - REACT_APP_DINING_URL=localhost:9500/dining
      - REACT_APP_CONFIG=fm
      - PORT=${FRONT_PORT}
    volumes:
      - ./self-service-kiosk/:/self-service-kiosk/
    entrypoint: "bash -c './wait-for-it.sh $${REACT_APP_GATEWAY} -- npm run start'"
    networks:
      - nestjs-restaurant-network

  front-end-bff:
    image: micro-restaurant/self-service-kiosk-bff
    depends_on:
      - bff
    ports:
      - "${FRONT_BFF_PORT}:${FRONT_BFF_PORT}"
    environment:
      - REACT_APP_BFF_HOST=localhost:${BFF_PORT}
      - REACT_APP_CONFIG=bff
      - PORT=${FRONT_BFF_PORT}
    volumes:
      - ./self-service-kiosk/:/self-service-kiosk/
    entrypoint: "bash -c './wait-for-it.sh -t 30 bff:${BFF_PORT} -- npm run start'"
    networks:
      - nestjs-restaurant-network

  bff:
    image: micro-restaurant/bff
    ports:
      - "${BFF_PORT}:${BFF_PORT}"
    depends_on:
      - ${GATEWAY}
      - ${MENU_SERVICE}
      - ${KITCHEN_SERVICE}
      - ${DINING_SERVICE}
    environment:
      - GATEWAY_URL_WITH_PORT=${GATEWAY}:3000
      - MENU_SERVICE_URL_WITH_PORT=${GATEWAY}:3000/menu
      - KITCHEN_URL=${GATEWAY}:3000/kitchen
      - DINING_SERVICE_URL_WITH_PORT=${GATEWAY}:3000/dining
      - BFF_PORT=${BFF_PORT}
    volumes:
      - ./bff/:/bff/
    entrypoint: "bash -c './wait-for-it.sh $${GATEWAY_URL_WITH_PORT} -- npm run start:dev'"
    networks:
      - nestjs-restaurant-network

networks:
  nestjs-restaurant-network:
    driver: bridge